[package]
name = "theos"
version = "0.1.0"
edition = "2024"
license="MIT"


[profile.dev]
panic="abort"

[profile.release]
opt-level = 3
strip = true
debug = false
lto = true
codegen-units = 1
panic = "abort"


[dependencies]
bootloader = "0.9.23"

[[bin]]
name = "theos"
path = "src/main.rs"


